### PR TITLE
Change node-sass version from 5.0.0 to 4.12.0

### PR DESCRIPTION
**Pull request by duythien0912**
Because all other projects current using 4.12.0

https://github.com/tendermint/dex-demo/blob/d82e84755131901a4ffac6bb2abf4c3f434d1ea8/ui/package.json#L36

https://github.com/tendermint/vue/blob/240fe66591ae55e0ba5d5e6b849502972cfc01e3/packages/template/package.json#L51

https://github.com/tendermint/vue/blob/240fe66591ae55e0ba5d5e6b849502972cfc01e3/packages/vue/package.json#L51

### CODE REVIEW

**Comment by duythien0912** [comment]
@clockworkgr 

Let use Node 14 LTS

**Comment by clockworkgr** [comment]
actually thanks for reminding me to archive this repo....the template actually lives in the monorepo now: https://github.com/tendermint/vue/tree/develop/packages/template

**Comment by duythien0912** [comment]
Somehow when I use
 
```bash
starport app github.com/duythien0912/minecat3
```

on vue/package.json it still using

```json
"node-sass": "^5.0.0"
```

**Comment by clockworkgr** [comment]
which version of starport are you using? the template version in the github repo is a subsequent one (will be released with starport v0.16) that fixes a bunch of dependecy issues.

**Comment by duythien0912** [comment]
I use starport version v0.15.1.

```
⋊> ~/d/h/m/vue on master  starport version                                                                                                                                                   17:47:32
starport version v0.15.1 darwin/amd64 -build date: 2021-04-01T08:17:55Z
```

**Comment by duythien0912** [comment]
Oke, so I think you can close this PR because this fix seems a bit redundant 🙌.

**Comment by clockworkgr** [comment]
Will do, thanks anyway! Please don't let that stop you contributing in the future. The https://github.com/tendermint/vue monorepo is the current primary repo for the starport frontend.

**Pull request closed without merging**
